[start:technical]{cacheinfo}<!--start:dateform-->{dateform}<!--end:dateform--><!--start:admin--><form action="{selfpath}" method="post">
<!--end:admin--><table cellpadding="0" cellspacing="0" id="technical">
<tr>
<td>
{oses}</td>
<td>
{osesversions}</td>
<td>
{robots}</td>
</tr>
<tr>
<td>
{browsers}</td>
<td>
{browsersversions}</td>
<td>
{screens}</td>
</tr>
<tr>
<td>
{websearchers}</td>
<td>
{flash}</td>
<td>
{proxy}</td>
</tr>
<tr>
<td>
{java}</td>
<td>
{javascript}</td>
<td>
{cookies}</td>
</tr>
</table>
<!--start:admin-->{adminbuttons}</form>
<!--end:admin-->[/end]